# We might have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "adlink-python"

BBFILE_PATTERN_adlink-python := "^${LAYERDIR}"
BBFILE_PRIORITY_adlink-python = "11"

LAYERSERIES_COMPAT_adlink-python = "kirkstone"

